<a href="https://colab.research.google.com/github/nitishkumarcse/PythonProgram/blob/main/numpyclasswork.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import requests

url = https://raw.githubusercontent.com/nitishkumarcse/PythonProgram/refs/heads/main/numpyclasswork.ipynb
response = requests.get(url)

text = response.text
print(text)
import numpy as np
num=np.array([20,30,25,40])
print(num)

In [ ]:
import numpy as np
#to create array
numbers=np.array([20,30,40,50,70,90])
print(numbers)

In [1]:
import numpy as np

# Create a 0's array with order 3,6,2 and integer data type
zeros_array = np.zeros((3, 6, 2), dtype=int)
print(zeros_array)

[[[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]]


In [4]:
import numpy as np

def get_even_factors_as_numpy_array(number):
    """
    Finds all even factors of a given number and returns them as a NumPy array.

    Args:
        number (int): The integer for which to find even factors.

    Returns:
        numpy.ndarray: A NumPy array containing the even factors.
                       Returns an empty array if no even factors are found.
    """
    if not isinstance(number, int) or number <= 0:
        raise ValueError("Input must be a positive integer.")

    even_factors = []
    for i in range(1, int(number**0.5) + 1):
        if number % i == 0:
            # Check if i is an even factor
            if i % 2 == 0:
                even_factors.append(i)
            # Check if number // i is an even factor (and different from i)
            if (number // i) % 2 == 0 and (number // i) != i:
                even_factors.append(number // i)

    # Sort the factors for a consistent output
    even_factors.sort()
    return np.array(even_factors)

# Example usage (you can uncomment and run this to test):
my_number = 100
factors_array = get_even_factors_as_numpy_array(my_number)
print(f"Even factors of {my_number}: {factors_array}")

# my_number = 7
# factors_array = get_even_factors_as_numpy_array(my_number)
# print(f"Even factors of {my_number}: {factors_array}")

Even factors of 100: [  2   4  10  20  50 100]


In [2]:
import numpy as np

# Create a 1's array with order 3,2,5 and integer data type
ones_array = np.ones((3, 2, 5), dtype=int)
print(ones_array)

[[[1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]]]
